#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include "test-temperature-sensor-impl.h"

/*
    This is an autogenerated function associated to
    SID: 60001
    Module: data
    Identifier: /TemperatureSensor:TemperatureSensorObject
    function params:
    Stable: False
*/

CoreconfValueT* read_TemperatureSensor_TemperatureSensorObject(void) {
    // TODO: Implement read logic for list/container
    // For now, return NULL
    return NULL;
}

/*
    This is an autogenerated function associated to
    SID: 60001
    Module: data
    Identifier: /TemperatureSensor:TemperatureSensorObject
    function params:
    Stable: False
*/

int write_TemperatureSensor_TemperatureSensorObject(CoreconfValueT* value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60002
    Module: data
    Identifier: /TemperatureSensor:TemperatureSensorObject/batteryLevel
    function params:
    Stable: False
*/

uint64_t read_TemperatureSensorObject_batteryLevel(void) {
    // TODO: replace with proper return value for the leaf "/TemperatureSensor:TemperatureSensorObject/batteryLevel"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60002
    Module: data
    Identifier: /TemperatureSensor:TemperatureSensorObject/batteryLevel
    function params:
    Stable: False
*/

int write_TemperatureSensorObject_batteryLevel(uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60003
    Module: data
    Identifier: /TemperatureSensor:TemperatureSensorObject/statusLED
    function params:
    Stable: False
*/

enum Temperaturesensorobject_StatusledEnum read_TemperatureSensorObject_statusLED(void) {
    // TODO: replace with proper return value for the leaf "/TemperatureSensor:TemperatureSensorObject/statusLED"
    enum Temperaturesensorobject_StatusledEnum mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60003
    Module: data
    Identifier: /TemperatureSensor:TemperatureSensorObject/statusLED
    function params:
    Stable: False
*/

int write_TemperatureSensorObject_statusLED(enum Temperaturesensorobject_StatusledEnum value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60004
    Module: data
    Identifier: /TemperatureSensor:TemperatureSensorObject/temperature
    function params:
    Stable: False
*/

CoreconfValueT* read_TemperatureSensorObject_temperature(void) {
    // TODO: Implement read logic for list/container
    // For now, return NULL
    return NULL;
}

/*
    This is an autogenerated function associated to
    SID: 60004
    Module: data
    Identifier: /TemperatureSensor:TemperatureSensorObject/temperature
    function params:
    Stable: False
*/

int write_TemperatureSensorObject_temperature(CoreconfValueT* value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60005
    Module: data
    Identifier: /TemperatureSensor:TemperatureSensorObject/temperature/voltageADC
    function params:
    Stable: False
*/

double read_temperature_voltageADC(void) {
    // TODO: replace with proper return value for the leaf "/TemperatureSensor:TemperatureSensorObject/temperature/voltageADC"
    double mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60005
    Module: data
    Identifier: /TemperatureSensor:TemperatureSensorObject/temperature/voltageADC
    function params:
    Stable: False
*/

int write_temperature_voltageADC(double value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/**
 * GET handler - Returns the coreconf model or a subset for GET requests
 *
 * @param coreconfModel - Pointer to the full coreconf model
 * @return CoreconfValueT* - The value to return in the GET response
 *                          By default returns the entire model, but can be
 *                          overridden to return a filtered subset
 *
 * Default behavior: Returns the entire coreconfModel
 * To customize: Implement logic to filter or transform the model
 */
CoreconfValueT* handleGetRequest(CoreconfValueT *coreconfModel) {
    // Default: return the entire model
    // To return a subset, implement your custom logic here
    return coreconfModel;
}

/**
 * PUT handler - Validates and replaces the coreconf model
 *
 * @param coreconfModel - Pointer to the current coreconf model
 * @param newValue - The new value to replace the model with
 * @param clookupHashmap - Pointer to the lookup hashmap that needs rebuilding
 * @return int - 0 on success, non-zero error code on failure
 *
 * This function performs validation and replaces the model on success
 */
int handlePutRequest(CoreconfValueT **coreconfModel, CoreconfValueT *newValue, struct hashmap **clookupHashmap) {
    if (coreconfModel == NULL || *coreconfModel == NULL || newValue == NULL) {
        printf("PUT validation failed: NULL pointer\n");
        return -1;
    }

    // Validate that both are hashmaps (required for top-level CORECONF model)
    if ((*coreconfModel)->type != CORECONF_HASHMAP || newValue->type != CORECONF_HASHMAP) {
        printf("PUT validation failed: Top-level must be a hashmap\n");
        return -2;
    }

    CoreconfHashMapT *currentMap = (*coreconfModel)->data.map_value;
    CoreconfHashMapT *newMap = newValue->data.map_value;

    if (currentMap == NULL || newMap == NULL) {
        printf("PUT validation failed: Invalid hashmap structure\n");
        return -3;
    }

    // Validate that the top-level SIDs match
    // The top-level map keys are the module SIDs
    if (currentMap->size == 0 || newMap->size == 0) {
        printf("PUT validation failed: Empty hashmaps\n");
        return -4;
    }

    // Check if top-level SIDs are compatible
    // Iterate through new hashmap and check if at least one SID exists in current map
    bool foundMatchingSID = false;
    for (size_t i = 0; i < HASHMAP_TABLE_SIZE && !foundMatchingSID; i++) {
        CoreconfObjectT *newEntry = newMap->table[i];
        while (newEntry != NULL) {
            uint64_t newSID = newEntry->key;

            // Check if this SID exists in the current map
            for (size_t j = 0; j < HASHMAP_TABLE_SIZE; j++) {
                CoreconfObjectT *currentEntry = currentMap->table[j];
                while (currentEntry != NULL) {
                    if (currentEntry->key == newSID) {
                        foundMatchingSID = true;
                        break;
                    }
                    currentEntry = currentEntry->next;
                }
                if (foundMatchingSID) {
                    break;
                }
            }

            if (foundMatchingSID) {
                break;
            }
            newEntry = newEntry->next;
        }
    }

    if (!foundMatchingSID) {
        printf("PUT validation failed: No matching top-level SIDs\n");
        return -5;
    }

    // TODO: Add any additional user-specific validation logic here
    // Return a non-zero error code to reject the PUT request

    // All validation passed - free old model and replace with new one
    freeCoreconf(*coreconfModel, true);
    *coreconfModel = newValue;

    // Rebuild lookup hashmap with the new model
    if (clookupHashmap != NULL && *clookupHashmap != NULL) {
        hashmap_free(*clookupHashmap);
        *clookupHashmap = hashmap_new(sizeof(CLookupT), 0, 0, 0, clookupHash, clookupCompare, clookupFree, NULL);
        buildCLookupHashmapFromCoreconf(*coreconfModel, *clookupHashmap, 0, 0);
        printf("PUT succeeded: Model replaced and lookup hashmap rebuilt\n");
    } else {
        printf("PUT succeeded: Model replaced (no lookup hashmap to rebuild)\n");
    }

    return 0;
}
