/* Generated by tools/prepareModel.py from TemperatureSensor.sid, TemperatureSensor.json. Do not edit. */
#include "test-temperature-sensor.h"

/* Instance data, CBOR-encoded by pycoreconf */
static const uint8_t instanceCBOR[] = {
    0xa1, 0x19, 0xea, 0x61, 0xa3, 0x02, 0x00, 0x01, 0x18, 0x57, 0x03, 0xa1,
    0x01, 0xfb, 0x3f, 0xfc, 0xcc, 0xcc, 0xcc, 0xcc, 0xcc, 0xcd,
};

/* Parent SID of every data node (0 = top level), from the schema */
static const long parentSIDs[] = {
    0, 60001, 60001, 60001, 60004,
};

/* Child SID -> its parent SIDs */
static const CLookupEntryT clookupTable[] = {
    { 60001, &parentSIDs[0], 1 },
    { 60002, &parentSIDs[1], 1 },
    { 60003, &parentSIDs[2], 1 },
    { 60004, &parentSIDs[3], 1 },
    { 60005, &parentSIDs[4], 1 },
};

/* Every item of the SID files */
static const SIDEntryT SIDTable[] = {
    { "TemperatureSensor", 60000, SID_NS_MODULE, 0, NULL, 0 },
    { "/TemperatureSensor:TemperatureSensorObject", 60001, SID_NS_DATA, 0, NULL, 0 },
    { "/TemperatureSensor:TemperatureSensorObject/batteryLevel", 60002, SID_NS_DATA, 0, NULL, 0 },
    { "/TemperatureSensor:TemperatureSensorObject/statusLED", 60003, SID_NS_DATA, 0, NULL, 0 },
    { "/TemperatureSensor:TemperatureSensorObject/temperature", 60004, SID_NS_DATA, 0, NULL, 0 },
    { "/TemperatureSensor:TemperatureSensorObject/temperature/voltageADC", 60005, SID_NS_DATA, 0, NULL, 0 },
};

const CoreconfModelDescT testTemperatureSensorModelDesc = {
    .instanceCBOR = instanceCBOR,
    .instanceCBORLen = sizeof(instanceCBOR),
    .keymapCBOR = NULL,
    .keymapCBORLen = 0,
    .SIDTable = SIDTable,
    .SIDCount = sizeof(SIDTable) / sizeof(SIDTable[0]),
    .keymapStatic = NULL,
    .keymapStaticCount = 0,
    .clookupStatic = clookupTable,
    .clookupStaticCount = sizeof(clookupTable) / sizeof(clookupTable[0]),
};
