#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <coreconf.h>

/*
    This is an autogenerated function associated to 
    SID: 1013
    Module: data 
    Identifier: /sensor:sensordata/dataReadings
    function params: /sensor:sensordata/dataReadings/readingIndex
    Stable: None
*/
json_t* get_dataReadings(json_t *instance, uint8_t readingIndex){
    json_t* leafValue;
    // A function call to find dataReading from the instance where the index of the list is equal to readingIndex
    int keys[] = {readingIndex}
    json_t* dataReading = searchInstance(instance, keys);

}

        


