#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include "test-schc-impl.h"

/*
    This is an autogenerated function associated to
    SID: 60095
    Module: data
    Identifier: /ietf-schc:schc
    function params:
    Stable: False
*/

CoreconfValueT* read_ietfSchc_schc(void) {
    // TODO: Implement read logic for list/container
    // For now, return NULL
    return NULL;
}

/*
    This is an autogenerated function associated to
    SID: 60095
    Module: data
    Identifier: /ietf-schc:schc
    function params:
    Stable: False
*/

int write_ietfSchc_schc(CoreconfValueT* value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60096
    Module: data
    Identifier: /ietf-schc:schc/rule
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

CoreconfValueT* read_schc_rule(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: Implement read logic for list/container
    // For now, return NULL
    return NULL;
}

/*
    This is an autogenerated function associated to
    SID: 60096
    Module: data
    Identifier: /ietf-schc:schc/rule
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_schc_rule(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, CoreconfValueT* value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60097
    Module: data
    Identifier: /ietf-schc:schc/rule/ack-behavior
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_ackBehavior(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/ack-behavior"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60097
    Module: data
    Identifier: /ietf-schc:schc/rule/ack-behavior
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_ackBehavior(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60098
    Module: data
    Identifier: /ietf-schc:schc/rule/direction
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_direction(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/direction"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60098
    Module: data
    Identifier: /ietf-schc:schc/rule/direction
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_direction(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60099
    Module: data
    Identifier: /ietf-schc:schc/rule/dtag-size
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_dtagSize(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/dtag-size"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60099
    Module: data
    Identifier: /ietf-schc:schc/rule/dtag-size
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_dtagSize(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60100
    Module: data
    Identifier: /ietf-schc:schc/rule/entry
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator
    Stable: False
*/

CoreconfValueT* read_rule_entry(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator) {
    // TODO: Implement read logic for list/container
    // For now, return NULL
    return NULL;
}

/*
    This is an autogenerated function associated to
    SID: 60100
    Module: data
    Identifier: /ietf-schc:schc/rule/entry
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator
    Stable: False
*/

int write_rule_entry(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, CoreconfValueT* value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60101
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/comp-decomp-action
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator
    Stable: False
*/

uint64_t read_entry_compDecompAction(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/entry/comp-decomp-action"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60101
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/comp-decomp-action
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator
    Stable: False
*/

int write_entry_compDecompAction(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60102
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/comp-decomp-action-value
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator , /ietf-schc:schc/rule/entry/comp-decomp-action-value/index
    Stable: False
*/

CoreconfValueT* read_entry_compDecompActionValue(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, uint64_t compDecompActionValue_index) {
    // TODO: Implement read logic for list/container
    // For now, return NULL
    return NULL;
}

/*
    This is an autogenerated function associated to
    SID: 60102
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/comp-decomp-action-value
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator , /ietf-schc:schc/rule/entry/comp-decomp-action-value/index
    Stable: False
*/

int write_entry_compDecompActionValue(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, uint64_t compDecompActionValue_index, CoreconfValueT* value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60104
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/comp-decomp-action-value/value
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator , /ietf-schc:schc/rule/entry/comp-decomp-action-value/index
    Stable: False
*/

bool read_compDecompActionValue_value(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, uint64_t compDecompActionValue_index) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/entry/comp-decomp-action-value/value"
    bool mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60104
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/comp-decomp-action-value/value
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator , /ietf-schc:schc/rule/entry/comp-decomp-action-value/index
    Stable: False
*/

int write_compDecompActionValue_value(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, uint64_t compDecompActionValue_index, bool value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60107
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/field-length
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator
    Stable: False
*/

CoreconfValueT* read_entry_fieldLength(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator) {
    // TODO: Implement read logic for list/container
    // For now, return NULL
    return NULL;
}

/*
    This is an autogenerated function associated to
    SID: 60107
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/field-length
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator
    Stable: False
*/

int write_entry_fieldLength(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, CoreconfValueT* value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60109
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/matching-operator
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator
    Stable: False
*/

uint64_t read_entry_matchingOperator(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/entry/matching-operator"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60109
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/matching-operator
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator
    Stable: False
*/

int write_entry_matchingOperator(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60110
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/matching-operator-value
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator , /ietf-schc:schc/rule/entry/matching-operator-value/index
    Stable: False
*/

CoreconfValueT* read_entry_matchingOperatorValue(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, uint64_t matchingOperatorValue_index) {
    // TODO: Implement read logic for list/container
    // For now, return NULL
    return NULL;
}

/*
    This is an autogenerated function associated to
    SID: 60110
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/matching-operator-value
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator , /ietf-schc:schc/rule/entry/matching-operator-value/index
    Stable: False
*/

int write_entry_matchingOperatorValue(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, uint64_t matchingOperatorValue_index, CoreconfValueT* value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60112
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/matching-operator-value/value
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator , /ietf-schc:schc/rule/entry/matching-operator-value/index
    Stable: False
*/

bool read_matchingOperatorValue_value(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, uint64_t matchingOperatorValue_index) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/entry/matching-operator-value/value"
    bool mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60112
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/matching-operator-value/value
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator , /ietf-schc:schc/rule/entry/matching-operator-value/index
    Stable: False
*/

int write_matchingOperatorValue_value(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, uint64_t matchingOperatorValue_index, bool value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60113
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/target-value
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator , /ietf-schc:schc/rule/entry/target-value/index
    Stable: False
*/

CoreconfValueT* read_entry_targetValue(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, uint64_t targetValue_index) {
    // TODO: Implement read logic for list/container
    // For now, return NULL
    return NULL;
}

/*
    This is an autogenerated function associated to
    SID: 60113
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/target-value
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator , /ietf-schc:schc/rule/entry/target-value/index
    Stable: False
*/

int write_entry_targetValue(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, uint64_t targetValue_index, CoreconfValueT* value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60115
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/target-value/value
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator , /ietf-schc:schc/rule/entry/target-value/index
    Stable: False
*/

bool read_targetValue_value(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, uint64_t targetValue_index) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/entry/target-value/value"
    bool mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60115
    Module: data
    Identifier: /ietf-schc:schc/rule/entry/target-value/value
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length , /ietf-schc:schc/rule/entry/field-id , /ietf-schc:schc/rule/entry/field-position , /ietf-schc:schc/rule/entry/direction-indicator , /ietf-schc:schc/rule/entry/target-value/index
    Stable: False
*/

int write_targetValue_value(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t entry_fieldId, uint64_t entry_fieldPosition, uint64_t entry_directionIndicator, uint64_t targetValue_index, bool value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60116
    Module: data
    Identifier: /ietf-schc:schc/rule/fcn-size
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_fcnSize(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/fcn-size"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60116
    Module: data
    Identifier: /ietf-schc:schc/rule/fcn-size
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_fcnSize(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60117
    Module: data
    Identifier: /ietf-schc:schc/rule/fragmentation-mode
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_fragmentationMode(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/fragmentation-mode"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60117
    Module: data
    Identifier: /ietf-schc:schc/rule/fragmentation-mode
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_fragmentationMode(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60118
    Module: data
    Identifier: /ietf-schc:schc/rule/inactivity-timer
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

CoreconfValueT* read_rule_inactivityTimer(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: Implement read logic for list/container
    // For now, return NULL
    return NULL;
}

/*
    This is an autogenerated function associated to
    SID: 60118
    Module: data
    Identifier: /ietf-schc:schc/rule/inactivity-timer
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_inactivityTimer(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, CoreconfValueT* value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60119
    Module: data
    Identifier: /ietf-schc:schc/rule/inactivity-timer/ticks-duration
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_inactivityTimer_ticksDuration(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/inactivity-timer/ticks-duration"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60119
    Module: data
    Identifier: /ietf-schc:schc/rule/inactivity-timer/ticks-duration
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_inactivityTimer_ticksDuration(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60120
    Module: data
    Identifier: /ietf-schc:schc/rule/inactivity-timer/ticks-numbers
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_inactivityTimer_ticksNumbers(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/inactivity-timer/ticks-numbers"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60120
    Module: data
    Identifier: /ietf-schc:schc/rule/inactivity-timer/ticks-numbers
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_inactivityTimer_ticksNumbers(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60121
    Module: data
    Identifier: /ietf-schc:schc/rule/l2-word-size
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_l2WordSize(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/l2-word-size"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60121
    Module: data
    Identifier: /ietf-schc:schc/rule/l2-word-size
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_l2WordSize(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60122
    Module: data
    Identifier: /ietf-schc:schc/rule/max-ack-requests
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_maxAckRequests(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/max-ack-requests"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60122
    Module: data
    Identifier: /ietf-schc:schc/rule/max-ack-requests
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_maxAckRequests(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60123
    Module: data
    Identifier: /ietf-schc:schc/rule/max-interleaved-frames
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_maxInterleavedFrames(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/max-interleaved-frames"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60123
    Module: data
    Identifier: /ietf-schc:schc/rule/max-interleaved-frames
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_maxInterleavedFrames(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60124
    Module: data
    Identifier: /ietf-schc:schc/rule/maximum-packet-size
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_maximumPacketSize(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/maximum-packet-size"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60124
    Module: data
    Identifier: /ietf-schc:schc/rule/maximum-packet-size
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_maximumPacketSize(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60125
    Module: data
    Identifier: /ietf-schc:schc/rule/rcs-algorithm
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_rcsAlgorithm(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/rcs-algorithm"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60125
    Module: data
    Identifier: /ietf-schc:schc/rule/rcs-algorithm
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_rcsAlgorithm(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60126
    Module: data
    Identifier: /ietf-schc:schc/rule/retransmission-timer
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

CoreconfValueT* read_rule_retransmissionTimer(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: Implement read logic for list/container
    // For now, return NULL
    return NULL;
}

/*
    This is an autogenerated function associated to
    SID: 60126
    Module: data
    Identifier: /ietf-schc:schc/rule/retransmission-timer
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_retransmissionTimer(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, CoreconfValueT* value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60127
    Module: data
    Identifier: /ietf-schc:schc/rule/retransmission-timer/ticks-duration
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_retransmissionTimer_ticksDuration(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/retransmission-timer/ticks-duration"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60127
    Module: data
    Identifier: /ietf-schc:schc/rule/retransmission-timer/ticks-duration
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_retransmissionTimer_ticksDuration(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60128
    Module: data
    Identifier: /ietf-schc:schc/rule/retransmission-timer/ticks-numbers
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_retransmissionTimer_ticksNumbers(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/retransmission-timer/ticks-numbers"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60128
    Module: data
    Identifier: /ietf-schc:schc/rule/retransmission-timer/ticks-numbers
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_retransmissionTimer_ticksNumbers(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60131
    Module: data
    Identifier: /ietf-schc:schc/rule/rule-nature
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_ruleNature(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/rule-nature"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60131
    Module: data
    Identifier: /ietf-schc:schc/rule/rule-nature
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_ruleNature(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60132
    Module: data
    Identifier: /ietf-schc:schc/rule/tile-in-all-1
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_tileInAll1(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/tile-in-all-1"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60132
    Module: data
    Identifier: /ietf-schc:schc/rule/tile-in-all-1
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_tileInAll1(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60133
    Module: data
    Identifier: /ietf-schc:schc/rule/tile-size
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_tileSize(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/tile-size"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60133
    Module: data
    Identifier: /ietf-schc:schc/rule/tile-size
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_tileSize(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60134
    Module: data
    Identifier: /ietf-schc:schc/rule/w-size
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_wSize(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/w-size"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60134
    Module: data
    Identifier: /ietf-schc:schc/rule/w-size
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_wSize(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 60135
    Module: data
    Identifier: /ietf-schc:schc/rule/window-size
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_rule_windowSize(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/window-size"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 60135
    Module: data
    Identifier: /ietf-schc:schc/rule/window-size
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_rule_windowSize(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/*
    This is an autogenerated function associated to
    SID: 2000010
    Module: data
    Identifier: /ietf-schc:schc/rule/ietf-schc-oam:proxy-behavior
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

uint64_t read_ietfSchcOam_proxyBehavior(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength) {
    // TODO: replace with proper return value for the leaf "/ietf-schc:schc/rule/ietf-schc-oam:proxy-behavior"
    uint64_t mockValue = 0;
    return mockValue;
}

/*
    This is an autogenerated function associated to
    SID: 2000010
    Module: data
    Identifier: /ietf-schc:schc/rule/ietf-schc-oam:proxy-behavior
    function params:/ietf-schc:schc/rule/rule-id-value , /ietf-schc:schc/rule/rule-id-length
    Stable: False
*/

int write_ietfSchcOam_proxyBehavior(uint64_t rule_ruleIdValue, uint64_t rule_ruleIdLength, uint64_t value) {
    // TODO: Implement write logic for this SID
    // For now, just return success
    return 0;
}

/**
 * GET handler - Returns the coreconf model or a subset for GET requests
 *
 * @param coreconfModel - Pointer to the full coreconf model
 * @return CoreconfValueT* - The value to return in the GET response
 *                          By default returns the entire model, but can be
 *                          overridden to return a filtered subset
 *
 * Default behavior: Returns the entire coreconfModel
 * To customize: Implement logic to filter or transform the model
 */
CoreconfValueT* handleGetRequest(CoreconfValueT *coreconfModel) {
    // Default: return the entire model
    // To return a subset, implement your custom logic here
    return coreconfModel;
}

/**
 * PUT handler - Validates and replaces the coreconf model
 *
 * @param coreconfModel - Pointer to the current coreconf model
 * @param newValue - The new value to replace the model with
 * @param clookupHashmap - Pointer to the lookup hashmap that needs rebuilding
 * @return int - 0 on success, non-zero error code on failure
 *
 * This function performs validation and replaces the model on success
 */
int handlePutRequest(CoreconfValueT **coreconfModel, CoreconfValueT *newValue, struct hashmap **clookupHashmap) {
    if (coreconfModel == NULL || *coreconfModel == NULL || newValue == NULL) {
        printf("PUT validation failed: NULL pointer\n");
        return -1;
    }

    // Validate that both are hashmaps (required for top-level CORECONF model)
    if ((*coreconfModel)->type != CORECONF_HASHMAP || newValue->type != CORECONF_HASHMAP) {
        printf("PUT validation failed: Top-level must be a hashmap\n");
        return -2;
    }

    CoreconfHashMapT *currentMap = (*coreconfModel)->data.map_value;
    CoreconfHashMapT *newMap = newValue->data.map_value;

    if (currentMap == NULL || newMap == NULL) {
        printf("PUT validation failed: Invalid hashmap structure\n");
        return -3;
    }

    // Validate that the top-level SIDs match
    // The top-level map keys are the module SIDs
    if (currentMap->size == 0 || newMap->size == 0) {
        printf("PUT validation failed: Empty hashmaps\n");
        return -4;
    }

    // Check if top-level SIDs are compatible
    // Iterate through new hashmap and check if at least one SID exists in current map
    bool foundMatchingSID = false;
    for (size_t i = 0; i < HASHMAP_TABLE_SIZE && !foundMatchingSID; i++) {
        CoreconfObjectT *newEntry = newMap->table[i];
        while (newEntry != NULL) {
            uint64_t newSID = newEntry->key;

            // Check if this SID exists in the current map
            for (size_t j = 0; j < HASHMAP_TABLE_SIZE; j++) {
                CoreconfObjectT *currentEntry = currentMap->table[j];
                while (currentEntry != NULL) {
                    if (currentEntry->key == newSID) {
                        foundMatchingSID = true;
                        break;
                    }
                    currentEntry = currentEntry->next;
                }
                if (foundMatchingSID) {
                    break;
                }
            }

            if (foundMatchingSID) {
                break;
            }
            newEntry = newEntry->next;
        }
    }

    if (!foundMatchingSID) {
        printf("PUT validation failed: No matching top-level SIDs\n");
        return -5;
    }

    // TODO: Add any additional user-specific validation logic here
    // Return a non-zero error code to reject the PUT request

    // All validation passed - free old model and replace with new one
    freeCoreconf(*coreconfModel, true);
    *coreconfModel = newValue;

    // Rebuild lookup hashmap with the new model
    if (clookupHashmap != NULL && *clookupHashmap != NULL) {
        hashmap_free(*clookupHashmap);
        *clookupHashmap = hashmap_new(sizeof(CLookupT), 0, 0, 0, clookupHash, clookupCompare, clookupFree, NULL);
        buildCLookupHashmapFromCoreconf(*coreconfModel, *clookupHashmap, 0, 0);
        printf("PUT succeeded: Model replaced and lookup hashmap rebuilt\n");
    } else {
        printf("PUT succeeded: Model replaced (no lookup hashmap to rebuild)\n");
    }

    return 0;
}
