#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "sid_prototypes.h"

/*
    This is an autogenerated function associated to 
    SID: 1007
    Module: data 
    Identifier: /sensor:sensorHealth
    function params: 
    Stable: false
*/
void read_sensorHealth(void){
}


/*
    This is an autogenerated function associated to 
    SID: 1008
    Module: data 
    Identifier: /sensor:sensorHealth/healthReadings
    function params: /sensor:sensorHealth/healthReadings/readingIndex
    Stable: false
*/
void read_healthReadings(uint8_t readingIndex){
    // Initialize the leaf if it has a return type with a default value;
    
    // Do something with the leaf
    readingIndex++;
}
        


/*
    This is an autogenerated function associated to 
    SID: 1010
    Module: data 
    Identifier: /sensor:sensorHealth/healthReadings/healthValue
    function params: /sensor:sensorHealth/healthReadings/readingIndex
    Stable: false
*/
uint32_t read_healthValue(uint8_t readingIndex){
    // Initialize the leaf if it has a return type with a default value;
    uint32_t healthValueInstance  = 0;
	
    // Do something with the leaf
    // Return the leaf 
    readingIndex++;
    return healthValueInstance;
}
        


/*
    This is an autogenerated function associated to 
    SID: 1012
    Module: data 
    Identifier: /sensor:sensordata
    function params: 
    Stable: false
*/
void read_sensordata(void){
}


/*
    This is an autogenerated function associated to 
    SID: 1013
    Module: data 
    Identifier: /sensor:sensordata/dataReadings
    function params: /sensor:sensordata/dataReadings/readingIndex
    Stable: false
*/
void read_dataReadings(uint8_t readingIndex){
    // Initialize the leaf if it has a return type with a default value;
    
    // Do something with the leaf
    readingIndex++;
    
}
        


/*
    This is an autogenerated function associated to 
    SID: 1014
    Module: data 
    Identifier: /sensor:sensordata/dataReadings/dataValue
    function params: /sensor:sensordata/dataReadings/readingIndex
    Stable: false
*/
uint16_t read_dataValue(uint8_t readingIndex){
    // Initialize the leaf if it has a return type with a default value;
    uint16_t dataValueInstance  = 0;
	
    // Do something with the leaf
    // Return the leaf 
    readingIndex++;
    return dataValueInstance;
}
        

